# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11', '17']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Compile code
        run: mvn --batch-mode compile
      - name: Run tests
        run: mvn --batch-mode install
        timeout-minutes: 10
      - name: Generate Maven test report
        if: failure()
        run: mvn --batch-mode surefire-report:report-only
      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-report
          path: |
            target/surefire-reports
            target/site